### ISSUE TITLE
Documentation - LanguageClient-neovim usage

### ISSUE THREAD

**Issue by Samsinite** [emberwatch/ember-language-server#127]
Hi! Thanks for creating this awesome language server for ember.

I'm having trouble setting it up to work with vim using the LanguageClient-neovim plugin. The easiest way to set up language servers with this plugin is to specify how to run the language server over stdin. Ex: `javascript': ['/Users/samueljclopton/javascript-typescript-langserver/bin/language-server-stdio']` and `'ruby': ['solargraph stdio']`. Not quire sure what args `start-server.js` is expecting, so any help here would be appreciated.

**Comment by Turbo87** [comment]
@Samsinite AFAIK right now the language server here does not support stdio yet. but the underlying library that we used to implement it does have support for that. we should probably do some kind of CLI argument parsing and then decide whether to use IPC or stdio based on that.

**Comment by Samsinite** [comment]
Sounds good, is that something that you would like help with?

**Comment by Turbo87** [comment]
Yes, definitely!

**Comment by Samsinite** [comment]
Sweet. Any opinions on a CLI argument parser that you would like to use? Or would you like it to manually parse the arguments? What sort of CLI interface have you considered using? Looks like `javascript-language-server` uses [commander](https://github.com/tj/commander.js) if we want to consider what has worked well for another node language server.

**Comment by Turbo87** [comment]
> Any opinions on a CLI argument parser that you would like to use? Or would you like it to manually parse the arguments?

I guess for now something like `process.argv.includes('--stdio')` should be enough

**Comment by mrloop** [comment]
Your emberfest talk prompted me to take a look, thanks!

Took a quick survey of vim lsp clients

 | name                                                                       | stdio support | node-ipc support  |  stars  |
 | ---------------------                                                      | ------------- | ----------------- | ------- |
 | [ale](https://github.com/w0rp/ale)                                         |       x       |                   |  6381   |
 | [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) |       x       |                   |  1597   |
 | [vim-lsp](https://github.com/prabirshrestha/vim-lsp)                       |       x       |                   |  579    |
 | [coc.nvim](https://github.com/neoclide/coc.nvim)                           |       x       |        x          |  395    |

Support determined by searching repos for `stdio` and `ipc`, please correct if wrong, have minimal experience with vim LSP clients.

I'm using vim-lsp and wanted to know what other LSP clients I could use and if they'd support `ember-language-server`. Looks like to support greatest number of vim LSP clients `ember-language-server` should support `stdio` as well as `node-ipc`. There's a closed PR #52 which replaces IPC for stdio but it's got no review, and was closed by the author in favour of the client supporting IPC. @Turbo87 would you consider a PR adding stdio support while not removing IPC?

**Comment by Turbo87** [comment]
>  would you consider a PR adding stdio support while not removing IPC?

sure, that sounds like a good idea. I suppose we should add some sort of `--stdio` option to the LSP which then uses stdio instead of node-ipc.

**Comment by Samsinite** [comment]
Looks like this has support now, see https://github.com/emberwatch/ember-language-server/pull/152. Thanks @graemechapman!

**Comment by NullVoxPopuli** [comment]
what config do I need to use the ELS? want to try out @lifeart's component context branch :) 

I already have the ELS globally installed... but don't know what to do with it
