### ISSUE TITLE
watcher ignored files should be configurable

### ISSUE THREAD

**Issue by akatz** [emberwatch/ember-language-server#54]
It would be nice if this was configurable:
https://github.com/emberwatch/ember-language-server/blob/master/src/server.ts#L82-L90

My cpu usage spikes up to 100% on one of my cores when this plugin is enabled and I think it's due to big directories not in the stock exclude path.

**Comment by Turbo87** [comment]
we could also experiment whether using https://github.com/Axosoft/nsfw instead would improve the situation

**Comment by t-sauer** [comment]
Since files are not watched anymore since the last release, I think this issue can be closed.
