### ISSUE TITLE
Atom Plugin

### ISSUE THREAD

**Issue by caseywatts** [emberwatch/ember-language-server#78]
As of today, atom supports language servers too! Great news for the adoption of this project. What are next steps for making at atom plug-in?

http://blog.atom.io/2017/09/12/announcing-atom-ide.html

**Comment by t-sauer** [comment]
Work has already started a couple of months over here: https://github.com/josa42/atom-languageserver-ember

As far as I know there were some problems with some features of the language server, but it might be worth exploring if it is working better now and what we need to do to improve the support.

**Comment by caseywatts** [comment]
awesome!

I made a PR to add that to the README - when that goes in, it'll close this issue~
