### ISSUE TITLE
Ember language server burning 100% CPU

### ISSUE THREAD

**Issue by mariokostelac** [emberwatch/ember-language-server#92]
Hey,

I am working on quite a large codebase and language server burns my CPU on 100% for long periods, seeming to never finish (left it running for 30minutes).

How can I debug what's actually happening?

**Comment by lolmaus** [comment]
Are you sure it's `ember-language-server` and not https://github.com/Microsoft/vscode/issues/3998 ?

**Comment by t-sauer** [comment]
It is definitely a problem with the ember language server. See this comment for more information: https://github.com/emberwatch/vscode-ember/issues/4#issuecomment-351745467

**Comment by mariokostelac** [comment]
@lolmaus yes yes, it was definitely ember server. Today I saw the watcher burning 100% as well, but just when I started IDE and was done after several minutes.
